// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: config.proto

package proto_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceConfigOptions_ConfigOptionValueType int32

const (
	DeviceConfigOptions_STRING DeviceConfigOptions_ConfigOptionValueType = 0
	DeviceConfigOptions_INT32  DeviceConfigOptions_ConfigOptionValueType = 1
	DeviceConfigOptions_DOUBLE DeviceConfigOptions_ConfigOptionValueType = 2
	DeviceConfigOptions_BOOL   DeviceConfigOptions_ConfigOptionValueType = 3
)

// Enum value maps for DeviceConfigOptions_ConfigOptionValueType.
var (
	DeviceConfigOptions_ConfigOptionValueType_name = map[int32]string{
		0: "STRING",
		1: "INT32",
		2: "DOUBLE",
		3: "BOOL",
	}
	DeviceConfigOptions_ConfigOptionValueType_value = map[string]int32{
		"STRING": 0,
		"INT32":  1,
		"DOUBLE": 2,
		"BOOL":   3,
	}
)

func (x DeviceConfigOptions_ConfigOptionValueType) Enum() *DeviceConfigOptions_ConfigOptionValueType {
	p := new(DeviceConfigOptions_ConfigOptionValueType)
	*p = x
	return p
}

func (x DeviceConfigOptions_ConfigOptionValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceConfigOptions_ConfigOptionValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (DeviceConfigOptions_ConfigOptionValueType) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x DeviceConfigOptions_ConfigOptionValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceConfigOptions_ConfigOptionValueType.Descriptor instead.
func (DeviceConfigOptions_ConfigOptionValueType) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

type DeviceConfigOptions struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	DeviceId      string                              `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Options       []*DeviceConfigOptions_ConfigOption `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigOptions) Reset() {
	*x = DeviceConfigOptions{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigOptions) ProtoMessage() {}

func (x *DeviceConfigOptions) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigOptions.ProtoReflect.Descriptor instead.
func (*DeviceConfigOptions) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceConfigOptions) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceConfigOptions) GetOptions() []*DeviceConfigOptions_ConfigOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeviceConfigOptions_ConfigOption struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	ConfigName    string                                    `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigType    DeviceConfigOptions_ConfigOptionValueType `protobuf:"varint,2,opt,name=config_type,json=configType,proto3,enum=sensorhub.DeviceConfigOptions_ConfigOptionValueType" json:"config_type,omitempty"`
	StringValue   *string                                   `protobuf:"bytes,10,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
	IntValue      *int32                                    `protobuf:"varint,11,opt,name=int_value,json=intValue,proto3,oneof" json:"int_value,omitempty"`
	DoubleValue   *float64                                  `protobuf:"fixed64,12,opt,name=double_value,json=doubleValue,proto3,oneof" json:"double_value,omitempty"`
	FlagValue     *bool                                     `protobuf:"varint,13,opt,name=flag_value,json=flagValue,proto3,oneof" json:"flag_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigOptions_ConfigOption) Reset() {
	*x = DeviceConfigOptions_ConfigOption{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigOptions_ConfigOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigOptions_ConfigOption) ProtoMessage() {}

func (x *DeviceConfigOptions_ConfigOption) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigOptions_ConfigOption.ProtoReflect.Descriptor instead.
func (*DeviceConfigOptions_ConfigOption) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DeviceConfigOptions_ConfigOption) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *DeviceConfigOptions_ConfigOption) GetConfigType() DeviceConfigOptions_ConfigOptionValueType {
	if x != nil {
		return x.ConfigType
	}
	return DeviceConfigOptions_STRING
}

func (x *DeviceConfigOptions_ConfigOption) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

func (x *DeviceConfigOptions_ConfigOption) GetIntValue() int32 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *DeviceConfigOptions_ConfigOption) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *DeviceConfigOptions_ConfigOption) GetFlagValue() bool {
	if x != nil && x.FlagValue != nil {
		return *x.FlagValue
	}
	return false
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\tsensorhub\"\x9d\x04\n" +
	"\x13DeviceConfigOptions\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12E\n" +
	"\aoptions\x18\x02 \x03(\v2+.sensorhub.DeviceConfigOptions.ConfigOptionR\aoptions\x1a\xdb\x02\n" +
	"\fConfigOption\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12U\n" +
	"\vconfig_type\x18\x02 \x01(\x0e24.sensorhub.DeviceConfigOptions.ConfigOptionValueTypeR\n" +
	"configType\x12&\n" +
	"\fstring_value\x18\n" +
	" \x01(\tH\x00R\vstringValue\x88\x01\x01\x12 \n" +
	"\tint_value\x18\v \x01(\x05H\x01R\bintValue\x88\x01\x01\x12&\n" +
	"\fdouble_value\x18\f \x01(\x01H\x02R\vdoubleValue\x88\x01\x01\x12\"\n" +
	"\n" +
	"flag_value\x18\r \x01(\bH\x03R\tflagValue\x88\x01\x01B\x0f\n" +
	"\r_string_valueB\f\n" +
	"\n" +
	"_int_valueB\x0f\n" +
	"\r_double_valueB\r\n" +
	"\v_flag_value\"D\n" +
	"\x15ConfigOptionValueType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\t\n" +
	"\x05INT32\x10\x01\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x02\x12\b\n" +
	"\x04BOOL\x10\x03B\x0fZ\r./proto_typesb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_proto_goTypes = []any{
	(DeviceConfigOptions_ConfigOptionValueType)(0), // 0: sensorhub.DeviceConfigOptions.ConfigOptionValueType
	(*DeviceConfigOptions)(nil),                    // 1: sensorhub.DeviceConfigOptions
	(*DeviceConfigOptions_ConfigOption)(nil),       // 2: sensorhub.DeviceConfigOptions.ConfigOption
}
var file_config_proto_depIdxs = []int32{
	2, // 0: sensorhub.DeviceConfigOptions.options:type_name -> sensorhub.DeviceConfigOptions.ConfigOption
	0, // 1: sensorhub.DeviceConfigOptions.ConfigOption.config_type:type_name -> sensorhub.DeviceConfigOptions.ConfigOptionValueType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
