// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: measurement.proto

package proto_types

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorData_SensorValueType int32

const (
	SensorData_STRING SensorData_SensorValueType = 0
	SensorData_INT32  SensorData_SensorValueType = 1
	SensorData_DOUBLE SensorData_SensorValueType = 2
	SensorData_BOOL   SensorData_SensorValueType = 3
)

// Enum value maps for SensorData_SensorValueType.
var (
	SensorData_SensorValueType_name = map[int32]string{
		0: "STRING",
		1: "INT32",
		2: "DOUBLE",
		3: "BOOL",
	}
	SensorData_SensorValueType_value = map[string]int32{
		"STRING": 0,
		"INT32":  1,
		"DOUBLE": 2,
		"BOOL":   3,
	}
)

func (x SensorData_SensorValueType) Enum() *SensorData_SensorValueType {
	p := new(SensorData_SensorValueType)
	*p = x
	return p
}

func (x SensorData_SensorValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensorData_SensorValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_measurement_proto_enumTypes[0].Descriptor()
}

func (SensorData_SensorValueType) Type() protoreflect.EnumType {
	return &file_measurement_proto_enumTypes[0]
}

func (x SensorData_SensorValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SensorData_SensorValueType.Descriptor instead.
func (SensorData_SensorValueType) EnumDescriptor() ([]byte, []int) {
	return file_measurement_proto_rawDescGZIP(), []int{0, 0}
}

type SensorData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	DeviceId      string                    `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ip            *string                   `protobuf:"bytes,2,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	DeviceName    *string                   `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3,oneof" json:"device_name,omitempty"`
	Measurements  []*SensorData_Measurement `protobuf:"bytes,4,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_measurement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_measurement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_measurement_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SensorData) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *SensorData) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *SensorData) GetMeasurements() []*SensorData_Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type SensorData_Measurement struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	SensorType      string                     `protobuf:"bytes,1,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	SensorValueType SensorData_SensorValueType `protobuf:"varint,2,opt,name=sensor_value_type,json=sensorValueType,proto3,enum=sensorhub.SensorData_SensorValueType" json:"sensor_value_type,omitempty"`
	ReadTimestamp   *string                    `protobuf:"bytes,3,opt,name=read_timestamp,json=readTimestamp,proto3,oneof" json:"read_timestamp,omitempty"`
	SensorValueName *string                    `protobuf:"bytes,4,opt,name=sensor_value_name,json=sensorValueName,proto3,oneof" json:"sensor_value_name,omitempty"`
	StringValue     *string                    `protobuf:"bytes,10,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
	IntValue        *int32                     `protobuf:"varint,11,opt,name=int_value,json=intValue,proto3,oneof" json:"int_value,omitempty"`
	DoubleValue     *float64                   `protobuf:"fixed64,12,opt,name=double_value,json=doubleValue,proto3,oneof" json:"double_value,omitempty"`
	FlagValue       *bool                      `protobuf:"varint,13,opt,name=flag_value,json=flagValue,proto3,oneof" json:"flag_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SensorData_Measurement) Reset() {
	*x = SensorData_Measurement{}
	mi := &file_measurement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData_Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData_Measurement) ProtoMessage() {}

func (x *SensorData_Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_measurement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData_Measurement.ProtoReflect.Descriptor instead.
func (*SensorData_Measurement) Descriptor() ([]byte, []int) {
	return file_measurement_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SensorData_Measurement) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorData_Measurement) GetSensorValueType() SensorData_SensorValueType {
	if x != nil {
		return x.SensorValueType
	}
	return SensorData_STRING
}

func (x *SensorData_Measurement) GetReadTimestamp() string {
	if x != nil && x.ReadTimestamp != nil {
		return *x.ReadTimestamp
	}
	return ""
}

func (x *SensorData_Measurement) GetSensorValueName() string {
	if x != nil && x.SensorValueName != nil {
		return *x.SensorValueName
	}
	return ""
}

func (x *SensorData_Measurement) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

func (x *SensorData_Measurement) GetIntValue() int32 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *SensorData_Measurement) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *SensorData_Measurement) GetFlagValue() bool {
	if x != nil && x.FlagValue != nil {
		return *x.FlagValue
	}
	return false
}

var File_measurement_proto protoreflect.FileDescriptor

const file_measurement_proto_rawDesc = "" +
	"\n" +
	"\x11measurement.proto\x12\tsensorhub\"\xe1\x05\n" +
	"\n" +
	"SensorData\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x13\n" +
	"\x02ip\x18\x02 \x01(\tH\x00R\x02ip\x88\x01\x01\x12$\n" +
	"\vdevice_name\x18\x03 \x01(\tH\x01R\n" +
	"deviceName\x88\x01\x01\x12E\n" +
	"\fmeasurements\x18\x04 \x03(\v2!.sensorhub.SensorData.MeasurementR\fmeasurements\x1a\xdc\x03\n" +
	"\vMeasurement\x12\x1f\n" +
	"\vsensor_type\x18\x01 \x01(\tR\n" +
	"sensorType\x12Q\n" +
	"\x11sensor_value_type\x18\x02 \x01(\x0e2%.sensorhub.SensorData.SensorValueTypeR\x0fsensorValueType\x12*\n" +
	"\x0eread_timestamp\x18\x03 \x01(\tH\x00R\rreadTimestamp\x88\x01\x01\x12/\n" +
	"\x11sensor_value_name\x18\x04 \x01(\tH\x01R\x0fsensorValueName\x88\x01\x01\x12&\n" +
	"\fstring_value\x18\n" +
	" \x01(\tH\x02R\vstringValue\x88\x01\x01\x12 \n" +
	"\tint_value\x18\v \x01(\x05H\x03R\bintValue\x88\x01\x01\x12&\n" +
	"\fdouble_value\x18\f \x01(\x01H\x04R\vdoubleValue\x88\x01\x01\x12\"\n" +
	"\n" +
	"flag_value\x18\r \x01(\bH\x05R\tflagValue\x88\x01\x01B\x11\n" +
	"\x0f_read_timestampB\x14\n" +
	"\x12_sensor_value_nameB\x0f\n" +
	"\r_string_valueB\f\n" +
	"\n" +
	"_int_valueB\x0f\n" +
	"\r_double_valueB\r\n" +
	"\v_flag_value\">\n" +
	"\x0fSensorValueType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\t\n" +
	"\x05INT32\x10\x01\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x02\x12\b\n" +
	"\x04BOOL\x10\x03B\x05\n" +
	"\x03_ipB\x0e\n" +
	"\f_device_nameB\x0fZ\r./proto_typesb\x06proto3"

var (
	file_measurement_proto_rawDescOnce sync.Once
	file_measurement_proto_rawDescData []byte
)

func file_measurement_proto_rawDescGZIP() []byte {
	file_measurement_proto_rawDescOnce.Do(func() {
		file_measurement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_measurement_proto_rawDesc), len(file_measurement_proto_rawDesc)))
	})
	return file_measurement_proto_rawDescData
}

var file_measurement_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_measurement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_measurement_proto_goTypes = []any{
	(SensorData_SensorValueType)(0), // 0: sensorhub.SensorData.SensorValueType
	(*SensorData)(nil),              // 1: sensorhub.SensorData
	(*SensorData_Measurement)(nil),  // 2: sensorhub.SensorData.Measurement
}
var file_measurement_proto_depIdxs = []int32{
	2, // 0: sensorhub.SensorData.measurements:type_name -> sensorhub.SensorData.Measurement
	0, // 1: sensorhub.SensorData.Measurement.sensor_value_type:type_name -> sensorhub.SensorData.SensorValueType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_measurement_proto_init() }
func file_measurement_proto_init() {
	if File_measurement_proto != nil {
		return
	}
	file_measurement_proto_msgTypes[0].OneofWrappers = []any{}
	file_measurement_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_measurement_proto_rawDesc), len(file_measurement_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_measurement_proto_goTypes,
		DependencyIndexes: file_measurement_proto_depIdxs,
		EnumInfos:         file_measurement_proto_enumTypes,
		MessageInfos:      file_measurement_proto_msgTypes,
	}.Build()
	File_measurement_proto = out.File
	file_measurement_proto_goTypes = nil
	file_measurement_proto_depIdxs = nil
}
